version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "production"
    allowed_updates:
      - match:
          update_type: "security"
