---
kind: Template
apiVersion: v1
metadata:
  name: ${NAME}-deployment-template
  annotations:
    description:
      Deployment template for a django server connected to a PostGreSQL
      database.
    tags: django
    iconClass: icon-python
objects:
  - kind: NetworkSecurityPolicy
    apiVersion: security.devops.gov.bc.ca/v1alpha1
    metadata:
      name: pods-to-api
      labels:
        name: pods-to-api
        app: ${APP_NAME}
        env: ${TAG_NAME}
    spec:
      description: |
        Allow pods to talk to the internal api so deployments work.
        This only needs to be specified once per environment.
      source:
        - - $namespace=${NAMESPACE_NAME}-${TAG_NAME}
      destination:
        - - int:network=internal-cluster-api-endpoint

  - kind: ExternalNetwork
    apiVersion: security.devops.gov.bc.ca/v1alpha1
    metadata:
      name: ${NAME}
      network: ${NAME}
      labels:
        name: ${NAME}
        network: ${NAME}
        app: ${APP_NAME}
        env: ${TAG_NAME}
    spec:
      description: |
        Define the network parameters for accessing remote resources.
      entries:
        - ${OIDC_RP_HOST}
      servicePorts:
        - tcp/443

  - kind: NetworkSecurityPolicy
    apiVersion: security.devops.gov.bc.ca/v1alpha1
    metadata:
      name: ${NAME}
      labels:
        name: ${NAME}
        app: ${APP_NAME}
        env: ${TAG_NAME}
    spec:
      description: |
        Allow the application's API to talk to either the database or pdf microservice, plus a defined set of external resources.
      source:
        - - role=${ROLE}
          - app=${APP_NAME}
          - env=${TAG_NAME}
          - $namespace=${NAMESPACE_NAME}-${TAG_NAME}
      destination:
        - - role=db
          - app=${APP_NAME}
          - env=${TAG_NAME}
          - $namespace=${NAMESPACE_NAME}-${TAG_NAME}
        - - role=pdf
          - app=${APP_NAME}
          - env=${TAG_NAME}
          - $namespace=${NAMESPACE_NAME}-${TAG_NAME}
        - - ext:name=${NAME}

  - kind: Service
    apiVersion: v1
    metadata:
      name: ${NAME}
      labels:
        name: ${NAME}
        app: ${APP_NAME}
        role: ${ROLE}
        env: ${TAG_NAME}
      annotations:
        description: Exposes and load balances the application pods
        service.alpha.openshift.io/dependencies: "[{name: ${DATABASE_SERVICE_NAME}, kind: Service}]"
    spec:
      ports:
        - name: 8080-tcp
          port: 8080
          targetPort: 8080
      selector:
        name: ${NAME}

  - kind: Secret
    apiVersion: v1
    metadata:
      name: ${NAME}
      labels:
        name: ${NAME}
        app: ${APP_NAME}
        role: ${ROLE}
        env: ${TAG_NAME}
    stringData:
      oidc-rp-provider-endpoint: ${OIDC_RP_PROVIDER_ENDPOINT}
      oidc-rp-client-secret: ${OIDC_RP_CLIENT_SECRET}
      oidc-rp-host: ${OIDC_RP_HOST}
      encryption-key: ${DATA_SECURITY_KEY}
      efiling-auth-url: ${EFILING_AUTH_URL}
      efiling-client-id: ${EFILING_CLIENT_ID}
      efiling-client-secret: ${EFILING_CLIENT_SECRET}
      efiling-base-url: ${EFILING_BASE_URL}
      siteminder-logoff-url: ${SITEMINDER_LOGOFF_URL}
    type: Opaque

  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: ${NAME}
      labels:
        name: ${NAME}
        app: ${APP_NAME}
        role: ${ROLE}
        env: ${TAG_NAME}
      annotations:
        description: Defines how to deploy the application server
    spec:
      strategy:
        type: Rolling
      triggers:
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - ${NAME}
            from:
              kind: ImageStreamTag
              namespace: ${IMAGE_NAMESPACE}
              name: ${NAME}:${TAG_NAME}
        - type: ConfigChange
      replicas: 1
      selector:
        name: ${NAME}
      template:
        metadata:
          name: ${NAME}
          labels:
            name: ${NAME}
            app: ${APP_NAME}
            role: ${ROLE}
            env: ${TAG_NAME}
        spec:
          containers:
            - name: ${NAME}
              image:
              ports:
                - containerPort: 8080
                  protocol: TCP
              readinessProbe:
                initialDelaySeconds: 3
                timeoutSeconds: 30
                httpGet:
                  path: /health/
                  port: 8080
              livenessProbe:
                initialDelaySeconds: 120
                timeoutSeconds: 30
                httpGet:
                  path: /health/
                  port: 8080
              env:
                - name: DATABASE_SERVICE_NAME
                  value: ${DATABASE_SERVICE_NAME}
                - name: DATABASE_ENGINE
                  value: ${DATABASE_ENGINE}
                - name: DATABASE_NAME
                  valueFrom:
                    secretKeyRef:
                      name: ${DATABASE_DEPLOYMENT_NAME}
                      key: database-name
                - name: DATABASE_USER
                  valueFrom:
                    secretKeyRef:
                      name: ${DATABASE_DEPLOYMENT_NAME}
                      key: database-user
                - name: DATABASE_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: ${DATABASE_DEPLOYMENT_NAME}
                      key: database-password
                - name: APP_CONFIG
                  value: ${APP_CONFIG}
                - name: DJANGO_SECRET_KEY
                  value: ${DJANGO_SECRET_KEY}
                - name: DJANGO_DEBUG
                  value: ${DJANGO_DEBUG}
                - name: PDF_SERVICE_URL
                  value: ${PDF_SERVICE_URL}
                - name: OIDC_RP_PROVIDER_ENDPOINT
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}
                      key: oidc-rp-provider-endpoint
                - name: OIDC_RP_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}
                      key: oidc-rp-client-secret
                - name: OIDC_RP_KC_IDP_HINT
                  value: ${OIDC_RP_KC_IDP_HINT}

                - name: DATA_SECURITY_KEY
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}
                      key: encryption-key

                - name: EFILING_AUTH_URL
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}
                      key: efiling-auth-url
                - name: EFILING_CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}
                      key: efiling-client-id
                - name: EFILING_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}
                      key: efiling-client-secret
                - name: EFILING_BASE_URL
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}
                      key: efiling-base-url
                - name: SITEMINDER_LOGOFF_URL
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}
                      key: siteminder-logoff-url
              resources:
                requests:
                  cpu: ${CPU_REQUEST}
                  memory: ${MEMORY_REQUEST}
                limits:
                  cpu: ${CPU_LIMIT}
                  memory: ${MEMORY_LIMIT}

  - kind: HorizontalPodAutoscaler
    apiVersion: autoscaling/v1
    metadata:
      name: ${NAME}
      labels:
        name: ${NAME}
        app: ${APP_NAME}
        role: ${ROLE}
        env: ${TAG_NAME}
    spec:
      scaleTargetRef:
        kind: DeploymentConfig
        name: ${NAME}
      minReplicas: ${{MIN_REPLICAS}}
      maxReplicas: ${{MAX_REPLICAS}}

parameters:
  - name: NAME
    displayName: Name
    description: The name assigned to all of the OpenShift resources associated to the server instance.
    required: true
    value: api

  - name: APP_NAME
    displayName: App Name
    description: App Name
    required: true
    value: representation-grant
  - name: ROLE
    displayName: Role
    description: Role
    required: true
    value: api

  - name: NAMESPACE_NAME
    displayName: Namespace Name
    description: The base namespace name for the project.
    required: true
    value: 583dbf

  - name: IMAGE_NAMESPACE
    displayName: Image Namespace
    required: true
    description: The namespace of the OpenShift project containing the imagestream for the application.
    value: 583dbf-tools
  - name: DATABASE_SERVICE_NAME
    displayName: Database Service Name
    description: The name of the database server/service.
    required: true
    value: db
  - name: DATABASE_ENGINE
    displayName: Database Engine
    required: true
    description: "Database engine: postgresql, mysql, or sqlite (default)."
    value: postgresql
  - name: APP_CONFIG
    displayName: Application Configuration File Path
    description: Relative path to Gunicorn configuration file (optional).
  - name: DJANGO_SECRET_KEY
    displayName: Django Secret Key
    description: Set this to a long random string.
    generate: expression
    from: "[\\w]{50}"
  - name: DJANGO_DEBUG
    displayName: Django Debug
    description: If Django is in debug mode
    required: true
    value: "False"
  - name: PDF_SERVICE_URL
    displayName: PDF Service URL
    description: Internal URL to the PDF service.
    required: true
    value: http://pdf:5001
  - name: TAG_NAME
    displayName: Environment TAG name
    description: The TAG name for this environment, e.g., dev, test, prod
    value: dev
    required: true
  - name: DATABASE_DEPLOYMENT_NAME
    displayName: Database Deployment Name
    description: The name associated to the database deployment resources.  In particular, this is used to wire up the credentials associated to the database.
    required: true
    value: db

  - name: OIDC_RP_PROVIDER_ENDPOINT
    displayName: OIDC RP Provider Endpoint
    description: OIDC RP Provider Endpoint.
    required: false
    value:
  - name: OIDC_RP_HOST
    displayName: OIDC RP Hostname
    description: OIDC RP Hostname.  The api-deploy.overrides.sh will parse this from the supplied OIDC_RP_PROVIDER_ENDPOINT, and fetch it from a secret for updates.
    required: false
    value:
  - name: OIDC_RP_CLIENT_SECRET
    displayName: OIDC RP Client Secret
    description: OIDC RP Client Secret
    required: false
    value:
  - name: OIDC_RP_KC_IDP_HINT
    displayName: OIDC RP KeyCloak IDP Hint
    description: OIDC RP KeyCloak IDP Hint
    required: false
    value: bceid

  - name: DATA_SECURITY_KEY
    displayName: Data Security (Encryption) Key
    description: The Encryption Key for the environment.
    generate: expression
    from: "[a-zA-Z0-9]{32}"

  - name: EFILING_AUTH_URL
    displayName: EFILING authentication url
    description: EFILING authentication url
    required: false
    value:
  - name: EFILING_CLIENT_ID
    displayName: EFILING Service Client Id
    description: EFILING Service Client Id
    required: false
    value:
  - name: EFILING_CLIENT_SECRET
    displayName: EFILING Service Client Secret
    description: EFILING Service Client Secret
    required: false
    value:
  - name: EFILING_BASE_URL
    displayName: EFILING base url
    description: EFILING base url
    required: false
    value:

  - name: SITEMINDER_LOGOFF_URL
    displayName: Siteminder Logoff URL
    description: Siteminder Logoff URL
    required: false
    value:

  - name: MIN_REPLICAS
    displayName: Minimum Replicas
    description: The minimum number of pods to have running.
    required: true
    value: "3"
  - name: MAX_REPLICAS
    displayName: Maximum Replicas
    description: The maximum number of pods to have running.
    required: true
    value: "6"

  - name: CPU_REQUEST
    displayName: Resources CPU Request
    description: The resources CPU request (in cores) for this build.
    required: true
    value: 10m
  - name: CPU_LIMIT
    displayName: Resources CPU Limit
    description: The resources CPU limit (in cores) for this build.
    required: true
    value: 500m
  - name: MEMORY_REQUEST
    displayName: Resources Memory Request
    description: The resources Memory request (in Mi, Gi, etc) for this build.
    required: true
    value: 10Mi
  - name: MEMORY_LIMIT
    displayName: Resources Memory Limit
    description: The resources Memory limit (in Mi, Gi, etc) for this build.
    required: true
    value: 1Gi
